GET https://localhost:7160/todos

###
POST https://localhost:7160/todos
content-type: application/json
{
    "id": 3,
    "name":"write demo 3",
    "dueDate": "2024-06-30",
    "isCompleted": false
}

###
GET https://localhost:7160/todos/1

###
DELETE https://localhost:7160/todos/3

###
GET https://localhost:7160/tasks/1